apiVersion: v1
kind: Service
metadata:
  name: {{ include "pylord.fullname" . }}
  labels:
    {{- include "pylord.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "pylord.selectorLabels" . | nindent 4 }}
  ports:
    - name: telnet
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: telnet
